import { describe, expect, it } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import {
  callTotalOf, gateOf, lockFreqs, loadLock, potTypeOf, riverClassOf, riverContext, riverLine, toGtowLabel,
} from "./riverMes";

// Generated by analysis/pipeline/solve/river/livemes_fixture.py from recorded river spots: the Python
// reference (livemes_gate.py) computed every `expect` field. These tests fail on any drift between the two.
const fixture = JSON.parse(readFileSync(join(import.meta.dir, "riverMes.fixture.json"), "utf-8"));
const cases: any[] = fixture.cases;

describe("riverMes — pinned to the Python reference", () => {
  it("has a spread of fixture cases", () => {
    expect(cases.length).toBeGreaterThanOrEqual(8);
    expect(new Set(cases.map((c) => c.expect.ctx.hero)).size).toBe(2);
  });

  for (const c of cases) {
    it(`spot ${c.id}: context, lock cells, line and gate match`, () => {
      const ctx = riverContext(c.trace, c.preTokens)!;
      expect(ctx).toEqual(c.expect.ctx);

      const lock = loadLock();
      expect(lock).not.toBeNull();
      const { used } = lockFreqs(lock, ctx);
      expect(used).toEqual(c.expect.cells);

      const ln = riverLine(c.trace)!;
      expect(ln.line).toEqual(c.expect.line);
      expect(ln.extra).toEqual(c.expect.extra);

      const g = gateOf(c.dump, ctx.hero === "oop" ? 0 : 1, c.heroCards, { tau: 0.5, gMinBb: 0.1 });
      expect(g.ok).toBe(true);
      expect(g.G!).toBeCloseTo(c.expect.gate.G, 6);
      expect(g.L!).toBeCloseTo(c.expect.gate.L, 6);
      if (c.expect.gate.p_star == null) expect(g.pStar).toBe(Infinity);
      else expect(g.pStar!).toBeCloseTo(c.expect.gate.p_star, 6);
      expect(g.served).toBe(c.expect.gate.served);
      const top = (s: number[]) => g.actions![s.indexOf(Math.max(...s))];
      expect(top(g.mes!)).toBe(c.expect.gate.mes_top);
      expect(top(g.gto!)).toBe(c.expect.gate.gto_top);
    });
  }
});

describe("riverMes — pure pieces", () => {
  it("pot type counts preflop raises", () => {
    expect(potTypeOf(["F", "C", "X"])).toBe("limped");
    expect(potTypeOf(["F", "R2.5", "C"])).toBe("srp");
    expect(potTypeOf(["R2.5", "R9", "C"])).toBe("3bp");
    expect(potTypeOf(["R2.5", "R9", "R22", "C"])).toBe("3bp");
  });

  it("river class: flush and straight must ARRIVE on the river; a two-card wheel is not a straight", () => {
    expect(riverClassOf("2s5s9hKh7s")).toBe("flush");      // turn had two spades, river the third
    expect(riverClassOf("2s5s9sKh7d")).toBe("brick");      // flush already possible on the turn
    expect(riverClassOf("5s6h7dKc8s")).toBe("straight");   // one card now completes it
    expect(riverClassOf("5s6h7d8c2s")).toBe("brick");      // it was already there
    expect(riverClassOf("AsKh7d4c2s")).toBe("brick");      // A-2 + 3-5 needs both hole cards
    expect(riverClassOf("2c7dKhAsAc")).toBe("pair");
  });

  it("labels match the chain's labelOf exactly (sizes are street totals in bb)", () => {
    expect(toGtowLabel("Bet(1880)")).toEqual({ action: "BET 18.8", betsize: "18.8" });
    expect(toGtowLabel("Raise(4650)")).toEqual({ action: "RAISE 46.5", betsize: "46.5" });
    expect(toGtowLabel("AllIn(10400)")).toEqual({ action: "ALLIN 104", betsize: "104" });
    expect(toGtowLabel("Check")).toEqual({ action: "CHECK" });
    expect(toGtowLabel("Fold")).toEqual({ action: "FOLD" });
    expect(toGtowLabel("Call")).toEqual({ action: "CALL" });
    expect(toGtowLabel("Call", 18.8)).toEqual({ action: "CALL 18.8", betsize: "18.8" });
  });

  it("the call total comes from the chain's own hero node", () => {
    const facing = cases.find((c) => c.expect.line.length && String(c.expect.line.at(-1)).startsWith("~"));
    expect(facing).toBeDefined();
    const total = callTotalOf(facing.trace);
    const hn = facing.trace.nodes.filter((n: any) => n.street === "RIVER" && n.heroNode).pop();
    expect(total).toBe(hn.actions.find((a: any) => a.code === "C").betsize);
  });

  it("the gate charges nothing for deviating inside the equilibrium's indifference", () => {
    // two actions the equilibrium is indifferent between (same EV vs eq villain); the pool pays more for one
    const node = (strategy: number[][], ev: number[][]) => ({ actions: ["Check", "Bet(500)"], strategy, ev, weights: [1] });
    const x = {
      oop_holes: ["AsKs"], ip_holes: ["2c2d"],
      baseline: { nodes: [node([[0.5], [0.5]], [[100], [100]])] },
      exploit: { nodes: [node([[0], [1]], [[100], [300]])] },
    };
    const g = gateOf(x, 0, "AsKs", { tau: 0.5, gMinBb: 0.1 });
    expect(g.L).toBe(0);
    expect(g.pStar).toBeCloseTo(0, 9);
    expect(g.G).toBeCloseTo(1, 9);    // 1.0*3bb - (0.5*1 + 0.5*3)bb
    expect(g.served).toBe(true);
  });

  it("the gate refuses an exploit that only pays if you are nearly sure villain is the pool", () => {
    const node = (strategy: number[][], ev: number[][]) => ({ actions: ["Check", "Bet(500)"], strategy, ev, weights: [1] });
    const x = {
      oop_holes: ["AsKs"], ip_holes: ["2c2d"],
      baseline: { nodes: [node([[1], [0]], [[200], [-800]])] },      // betting is a big mistake vs eq
      exploit: { nodes: [node([[0], [1]], [[200], [260]])] },        // and a small gain vs the pool
    };
    const g = gateOf(x, 0, "AsKs", { tau: 0.5, gMinBb: 0.1 });
    expect(g.G).toBeCloseTo(0.6, 9);
    expect(g.L).toBeCloseTo(-10, 9);
    expect(g.pStar!).toBeGreaterThan(0.9);
    expect(g.served).toBe(false);
  });
});
