import { mesRiverLookup, extractLine } from "../services/mesRiver";
import { readFileSync } from "node:fs";
const locked = JSON.parse(readFileSync("../../../analysis/pipeline/limp_study/mes_handoff/runs/M2_heroBTN_srp_vs_BB_Kc7d2h.locked.json", "utf-8"));
const line = ["Check", "Check", "2c", "Check", "Bet(275)", "Call", "5s"];
const hit = await mesRiverLookup({ family: "M2_heroBTN_srp_vs_BB", board: "Kc7d2h", heroPlayer: 1, holesHint: locked.ip_holes, line, riverTokens: ["X"], heroCardsMapped: ["Ah", "Qs"] });
console.log("hit:", hit && { inRange: !hit.notInRange, actions: hit.actions });
const st = (await extractLine("M2_heroBTN_srp_vs_BB", "Kc7d2h", line))!;
const holes: string[] = locked.ip_holes;
const key = (cs: string[]) => [...cs].sort().join("");
const holeIdx = new Map(holes.map((hs, i) => [key([hs.slice(0, 2), hs.slice(2, 4)]), i]));
const idx = holeIdx.get(key(["Ah", "Qs"]));
console.log("idx via key:", idx, "| indexOf:", holes.indexOf("AhQs"), "| holes[idx]:", idx != null ? holes[idx] : null, "| w:", idx != null ? st.ip_weights[idx] : null);
const n0 = st.nodes.find((n) => n.history.join(",") === "0")!;
console.log("node[0] strat at idx:", idx != null ? n0.strategy.map((r) => r[idx]) : null);
process.exit(0);
